// Package report provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package report

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyScopes     = "apiKey.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GetTopCategoriesParamsMetric.
const (
	GetTopCategoriesParamsMetricAllowed    GetTopCategoriesParamsMetric = "allowed"
	GetTopCategoriesParamsMetricBlocked    GetTopCategoriesParamsMetric = "blocked"
	GetTopCategoriesParamsMetricRequests   GetTopCategoriesParamsMetric = "requests"
	GetTopCategoriesParamsMetricUnresolved GetTopCategoriesParamsMetric = "unresolved"
)

// Defines values for GetTopCategoriesParamsProtectionModule.
const (
	GetTopCategoriesParamsProtectionModuleAppBlocker        GetTopCategoriesParamsProtectionModule = "app_blocker"
	GetTopCategoriesParamsProtectionModuleContentFilter     GetTopCategoriesParamsProtectionModule = "content_filter"
	GetTopCategoriesParamsProtectionModuleMalwareProtection GetTopCategoriesParamsProtectionModule = "malware_protection"
)

// Defines values for GetTopCategoriesParamsReason.
const (
	GetTopCategoriesParamsReasonIpBlocker GetTopCategoriesParamsReason = "ip_blocker"
)

// Defines values for GetTopDomainsByCategoryParamsMetric.
const (
	GetTopDomainsByCategoryParamsMetricAllowed    GetTopDomainsByCategoryParamsMetric = "allowed"
	GetTopDomainsByCategoryParamsMetricBlocked    GetTopDomainsByCategoryParamsMetric = "blocked"
	GetTopDomainsByCategoryParamsMetricRequests   GetTopDomainsByCategoryParamsMetric = "requests"
	GetTopDomainsByCategoryParamsMetricUnresolved GetTopDomainsByCategoryParamsMetric = "unresolved"
)

// Defines values for GetTopDomainsByCategoryParamsProtectionModule.
const (
	GetTopDomainsByCategoryParamsProtectionModuleAppBlocker        GetTopDomainsByCategoryParamsProtectionModule = "app_blocker"
	GetTopDomainsByCategoryParamsProtectionModuleContentFilter     GetTopDomainsByCategoryParamsProtectionModule = "content_filter"
	GetTopDomainsByCategoryParamsProtectionModuleMalwareProtection GetTopDomainsByCategoryParamsProtectionModule = "malware_protection"
)

// Defines values for GetTopDomainsByCategoryParamsReason.
const (
	GetTopDomainsByCategoryParamsReasonIpBlocker GetTopDomainsByCategoryParamsReason = "ip_blocker"
)

// Defines values for GetHistoricalDnsLogsParamsActions.
const (
	DENIED     GetHistoricalDnsLogsParamsActions = "DENIED"
	GRANTED    GetHistoricalDnsLogsParamsActions = "GRANTED"
	UNRESOLVED GetHistoricalDnsLogsParamsActions = "UNRESOLVED"
)

// Defines values for GetHistoricalDnsLogsParamsReasons.
const (
	ALLOWLIST             GetHistoricalDnsLogsParamsReasons = "ALLOW_LIST"
	BINGSAFESEARCH        GetHistoricalDnsLogsParamsReasons = "BING_SAFESEARCH"
	BLOCKLIST             GetHistoricalDnsLogsParamsReasons = "BLOCK_LIST"
	CATEGORY              GetHistoricalDnsLogsParamsReasons = "CATEGORY"
	DUCKDCUCKGOSAFESEARCH GetHistoricalDnsLogsParamsReasons = "DUCKDCUCKGO_SAFESEARCH"
	GEOBLOCK              GetHistoricalDnsLogsParamsReasons = "GEO_BLOCK"
	GOOGLESAFESEARCH      GetHistoricalDnsLogsParamsReasons = "GOOGLE_SAFESEARCH"
	IPBLOCK               GetHistoricalDnsLogsParamsReasons = "IP_BLOCK"
	IPREMOVED             GetHistoricalDnsLogsParamsReasons = "IP_REMOVED"
	NOPOLICY              GetHistoricalDnsLogsParamsReasons = "NO_POLICY"
	YOUTUBESAFESEARCH     GetHistoricalDnsLogsParamsReasons = "YOUTUBE_SAFESEARCH"
)

// Defines values for GetTopDomainsParamsMetric.
const (
	Allowed    GetTopDomainsParamsMetric = "allowed"
	Blocked    GetTopDomainsParamsMetric = "blocked"
	Requests   GetTopDomainsParamsMetric = "requests"
	Unresolved GetTopDomainsParamsMetric = "unresolved"
)

// Defines values for GetTopDomainsParamsProtectionModule.
const (
	AppBlocker        GetTopDomainsParamsProtectionModule = "app_blocker"
	ContentFilter     GetTopDomainsParamsProtectionModule = "content_filter"
	MalwareProtection GetTopDomainsParamsProtectionModule = "malware_protection"
)

// Defines values for GetTopDomainsParamsReason.
const (
	IpBlocker GetTopDomainsParamsReason = "ip_blocker"
)

// Defines values for GetStatisticsParamsGranularity.
const (
	Daily   GetStatisticsParamsGranularity = "daily"
	Hourly  GetStatisticsParamsGranularity = "hourly"
	Monthly GetStatisticsParamsGranularity = "monthly"
)

// FlashStartErrorBody defines model for FlashStartErrorBody.
type FlashStartErrorBody struct {
	Code    string       `json:"code"`
	Details *interface{} `json:"details,omitempty"`
	Message *string      `json:"message,omitempty"`
}

// MissingCredentialsErrorBody defines model for MissingCredentialsErrorBody.
type MissingCredentialsErrorBody struct {
	Message string `json:"message"`
}

// BadRequestResponse defines model for BadRequest.
type BadRequestResponse = FlashStartErrorBody

// ForbiddenResponse defines model for Forbidden.
type ForbiddenResponse = FlashStartErrorBody

// NotFoundResponse defines model for NotFound.
type NotFoundResponse = FlashStartErrorBody

// ServerErrorResponse defines model for ServerError.
type ServerErrorResponse = FlashStartErrorBody

// UnauthorizedResponse defines model for Unauthorized.
type UnauthorizedResponse struct {
	union json.RawMessage
}

// GetTopCategoriesParams defines parameters for GetTopCategories.
type GetTopCategoriesParams struct {
	Start            time.Time                               `form:"start" json:"start"`
	End              time.Time                               `form:"end" json:"end"`
	Metric           *GetTopCategoriesParamsMetric           `form:"metric,omitempty" json:"metric,omitempty"`
	Limit            *float32                                `form:"limit,omitempty" json:"limit,omitempty"`
	CategoryIds      *[]openapi_types.UUID                   `form:"categoryIds,omitempty" json:"categoryIds,omitempty"`
	NetworkIds       *[]openapi_types.UUID                   `form:"networkIds,omitempty" json:"networkIds,omitempty"`
	OrganizationIds  *[]openapi_types.UUID                   `form:"organizationIds,omitempty" json:"organizationIds,omitempty"`
	PolicyIds        *[]openapi_types.UUID                   `form:"policyIds,omitempty" json:"policyIds,omitempty"`
	ProtectionModule *GetTopCategoriesParamsProtectionModule `form:"protectionModule,omitempty" json:"protectionModule,omitempty"`
	Reason           *GetTopCategoriesParamsReason           `form:"reason,omitempty" json:"reason,omitempty"`
}

// GetTopCategoriesParamsMetric defines parameters for GetTopCategories.
type GetTopCategoriesParamsMetric string

// GetTopCategoriesParamsProtectionModule defines parameters for GetTopCategories.
type GetTopCategoriesParamsProtectionModule string

// GetTopCategoriesParamsReason defines parameters for GetTopCategories.
type GetTopCategoriesParamsReason string

// GetTopDomainsByCategoryParams defines parameters for GetTopDomainsByCategory.
type GetTopDomainsByCategoryParams struct {
	Start            time.Time                                      `form:"start" json:"start"`
	End              time.Time                                      `form:"end" json:"end"`
	CategoryIds      []openapi_types.UUID                           `form:"categoryIds" json:"categoryIds"`
	Metric           *GetTopDomainsByCategoryParamsMetric           `form:"metric,omitempty" json:"metric,omitempty"`
	Limit            *float32                                       `form:"limit,omitempty" json:"limit,omitempty"`
	NetworkIds       *[]openapi_types.UUID                          `form:"networkIds,omitempty" json:"networkIds,omitempty"`
	OrganizationIds  *[]openapi_types.UUID                          `form:"organizationIds,omitempty" json:"organizationIds,omitempty"`
	PolicyIds        *[]openapi_types.UUID                          `form:"policyIds,omitempty" json:"policyIds,omitempty"`
	ProtectionModule *GetTopDomainsByCategoryParamsProtectionModule `form:"protectionModule,omitempty" json:"protectionModule,omitempty"`
	Reason           *GetTopDomainsByCategoryParamsReason           `form:"reason,omitempty" json:"reason,omitempty"`
}

// GetTopDomainsByCategoryParamsMetric defines parameters for GetTopDomainsByCategory.
type GetTopDomainsByCategoryParamsMetric string

// GetTopDomainsByCategoryParamsProtectionModule defines parameters for GetTopDomainsByCategory.
type GetTopDomainsByCategoryParamsProtectionModule string

// GetTopDomainsByCategoryParamsReason defines parameters for GetTopDomainsByCategory.
type GetTopDomainsByCategoryParamsReason string

// GetHistoricalDnsLogsParams defines parameters for GetHistoricalDnsLogs.
type GetHistoricalDnsLogsParams struct {
	Start           time.Time                            `form:"start" json:"start"`
	End             time.Time                            `form:"end" json:"end"`
	Limit           *float32                             `form:"limit,omitempty" json:"limit,omitempty"`
	Offset          *float32                             `form:"offset,omitempty" json:"offset,omitempty"`
	Actions         *[]GetHistoricalDnsLogsParamsActions `form:"actions,omitempty" json:"actions,omitempty"`
	CategoryIds     *[]openapi_types.UUID                `form:"categoryIds,omitempty" json:"categoryIds,omitempty"`
	FqdnSearch      *string                              `form:"fqdnSearch,omitempty" json:"fqdnSearch,omitempty"`
	NetworkIds      *[]openapi_types.UUID                `form:"networkIds,omitempty" json:"networkIds,omitempty"`
	OrganizationIds *[]openapi_types.UUID                `form:"organizationIds,omitempty" json:"organizationIds,omitempty"`
	PolicyIds       *[]openapi_types.UUID                `form:"policyIds,omitempty" json:"policyIds,omitempty"`
	Reasons         *[]GetHistoricalDnsLogsParamsReasons `form:"reasons,omitempty" json:"reasons,omitempty"`
}

// GetHistoricalDnsLogsParamsActions defines parameters for GetHistoricalDnsLogs.
type GetHistoricalDnsLogsParamsActions string

// GetHistoricalDnsLogsParamsReasons defines parameters for GetHistoricalDnsLogs.
type GetHistoricalDnsLogsParamsReasons string

// GetTopDomainsParams defines parameters for GetTopDomains.
type GetTopDomainsParams struct {
	Start            time.Time                            `form:"start" json:"start"`
	End              time.Time                            `form:"end" json:"end"`
	Metric           *GetTopDomainsParamsMetric           `form:"metric,omitempty" json:"metric,omitempty"`
	Limit            *float32                             `form:"limit,omitempty" json:"limit,omitempty"`
	CategoryIds      *[]openapi_types.UUID                `form:"categoryIds,omitempty" json:"categoryIds,omitempty"`
	NetworkIds       *[]openapi_types.UUID                `form:"networkIds,omitempty" json:"networkIds,omitempty"`
	OrganizationIds  *[]openapi_types.UUID                `form:"organizationIds,omitempty" json:"organizationIds,omitempty"`
	PolicyIds        *[]openapi_types.UUID                `form:"policyIds,omitempty" json:"policyIds,omitempty"`
	ProtectionModule *GetTopDomainsParamsProtectionModule `form:"protectionModule,omitempty" json:"protectionModule,omitempty"`
	Reason           *GetTopDomainsParamsReason           `form:"reason,omitempty" json:"reason,omitempty"`
}

// GetTopDomainsParamsMetric defines parameters for GetTopDomains.
type GetTopDomainsParamsMetric string

// GetTopDomainsParamsProtectionModule defines parameters for GetTopDomains.
type GetTopDomainsParamsProtectionModule string

// GetTopDomainsParamsReason defines parameters for GetTopDomains.
type GetTopDomainsParamsReason string

// GetStatisticsParams defines parameters for GetStatistics.
type GetStatisticsParams struct {
	Start           time.Time                       `form:"start" json:"start"`
	End             time.Time                       `form:"end" json:"end"`
	Granularity     *GetStatisticsParamsGranularity `form:"granularity,omitempty" json:"granularity,omitempty"`
	NetworkIds      *[]openapi_types.UUID           `form:"networkIds,omitempty" json:"networkIds,omitempty"`
	OrganizationIds *[]openapi_types.UUID           `form:"organizationIds,omitempty" json:"organizationIds,omitempty"`
	PolicyIds       *[]openapi_types.UUID           `form:"policyIds,omitempty" json:"policyIds,omitempty"`
}

// GetStatisticsParamsGranularity defines parameters for GetStatistics.
type GetStatisticsParamsGranularity string

// AsMissingCredentialsErrorBody returns the union data inside the UnauthorizedResponse as a MissingCredentialsErrorBody
func (t UnauthorizedResponse) AsMissingCredentialsErrorBody() (MissingCredentialsErrorBody, error) {
	var body MissingCredentialsErrorBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMissingCredentialsErrorBody overwrites any union data inside the UnauthorizedResponse as the provided MissingCredentialsErrorBody
func (t *UnauthorizedResponse) FromMissingCredentialsErrorBody(v MissingCredentialsErrorBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMissingCredentialsErrorBody performs a merge with any union data inside the UnauthorizedResponse, using the provided MissingCredentialsErrorBody
func (t *UnauthorizedResponse) MergeMissingCredentialsErrorBody(v MissingCredentialsErrorBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFlashStartErrorBody returns the union data inside the UnauthorizedResponse as a FlashStartErrorBody
func (t UnauthorizedResponse) AsFlashStartErrorBody() (FlashStartErrorBody, error) {
	var body FlashStartErrorBody
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFlashStartErrorBody overwrites any union data inside the UnauthorizedResponse as the provided FlashStartErrorBody
func (t *UnauthorizedResponse) FromFlashStartErrorBody(v FlashStartErrorBody) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFlashStartErrorBody performs a merge with any union data inside the UnauthorizedResponse, using the provided FlashStartErrorBody
func (t *UnauthorizedResponse) MergeFlashStartErrorBody(v FlashStartErrorBody) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UnauthorizedResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *UnauthorizedResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetTopCategories request
	GetTopCategories(ctx context.Context, params *GetTopCategoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTopDomainsByCategory request
	GetTopDomainsByCategory(ctx context.Context, params *GetTopDomainsByCategoryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCustomersReportDashboard request
	GetCustomersReportDashboard(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHistoricalDnsLogs request
	GetHistoricalDnsLogs(ctx context.Context, params *GetHistoricalDnsLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTopDomains request
	GetTopDomains(ctx context.Context, params *GetTopDomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetStatistics request
	GetStatistics(ctx context.Context, params *GetStatisticsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetTopCategories(ctx context.Context, params *GetTopCategoriesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTopCategoriesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTopDomainsByCategory(ctx context.Context, params *GetTopDomainsByCategoryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTopDomainsByCategoryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCustomersReportDashboard(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCustomersReportDashboardRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHistoricalDnsLogs(ctx context.Context, params *GetHistoricalDnsLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHistoricalDnsLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTopDomains(ctx context.Context, params *GetTopDomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTopDomainsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetStatistics(ctx context.Context, params *GetStatisticsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetStatisticsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetTopCategoriesRequest generates requests for GetTopCategories
func NewGetTopCategoriesRequest(server string, params *GetTopCategoriesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/categories")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, params.Start); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, params.End); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Metric != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "metric", runtime.ParamLocationQuery, *params.Metric); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CategoryIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "categoryIds", runtime.ParamLocationQuery, *params.CategoryIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkIds", runtime.ParamLocationQuery, *params.NetworkIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationIds", runtime.ParamLocationQuery, *params.OrganizationIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicyIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policyIds", runtime.ParamLocationQuery, *params.PolicyIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProtectionModule != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "protectionModule", runtime.ParamLocationQuery, *params.ProtectionModule); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Reason != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reason", runtime.ParamLocationQuery, *params.Reason); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTopDomainsByCategoryRequest generates requests for GetTopDomainsByCategory
func NewGetTopDomainsByCategoryRequest(server string, params *GetTopDomainsByCategoryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/categories/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, params.Start); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, params.End); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "categoryIds", runtime.ParamLocationQuery, params.CategoryIds); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Metric != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "metric", runtime.ParamLocationQuery, *params.Metric); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkIds", runtime.ParamLocationQuery, *params.NetworkIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationIds", runtime.ParamLocationQuery, *params.OrganizationIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicyIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policyIds", runtime.ParamLocationQuery, *params.PolicyIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProtectionModule != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "protectionModule", runtime.ParamLocationQuery, *params.ProtectionModule); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Reason != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reason", runtime.ParamLocationQuery, *params.Reason); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCustomersReportDashboardRequest generates requests for GetCustomersReportDashboard
func NewGetCustomersReportDashboardRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/customers-dashboard")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHistoricalDnsLogsRequest generates requests for GetHistoricalDnsLogs
func NewGetHistoricalDnsLogsRequest(server string, params *GetHistoricalDnsLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/dns-logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, params.Start); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, params.End); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Actions != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "actions", runtime.ParamLocationQuery, *params.Actions); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CategoryIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "categoryIds", runtime.ParamLocationQuery, *params.CategoryIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FqdnSearch != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fqdnSearch", runtime.ParamLocationQuery, *params.FqdnSearch); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkIds", runtime.ParamLocationQuery, *params.NetworkIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationIds", runtime.ParamLocationQuery, *params.OrganizationIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicyIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policyIds", runtime.ParamLocationQuery, *params.PolicyIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Reasons != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reasons", runtime.ParamLocationQuery, *params.Reasons); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTopDomainsRequest generates requests for GetTopDomains
func NewGetTopDomainsRequest(server string, params *GetTopDomainsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, params.Start); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, params.End); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Metric != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "metric", runtime.ParamLocationQuery, *params.Metric); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CategoryIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "categoryIds", runtime.ParamLocationQuery, *params.CategoryIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkIds", runtime.ParamLocationQuery, *params.NetworkIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationIds", runtime.ParamLocationQuery, *params.OrganizationIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicyIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policyIds", runtime.ParamLocationQuery, *params.PolicyIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProtectionModule != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "protectionModule", runtime.ParamLocationQuery, *params.ProtectionModule); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Reason != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reason", runtime.ParamLocationQuery, *params.Reason); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetStatisticsRequest generates requests for GetStatistics
func NewGetStatisticsRequest(server string, params *GetStatisticsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/statistics")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, params.Start); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, params.End); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Granularity != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "granularity", runtime.ParamLocationQuery, *params.Granularity); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkIds", runtime.ParamLocationQuery, *params.NetworkIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationIds", runtime.ParamLocationQuery, *params.OrganizationIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PolicyIds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "policyIds", runtime.ParamLocationQuery, *params.PolicyIds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetTopCategoriesWithResponse request
	GetTopCategoriesWithResponse(ctx context.Context, params *GetTopCategoriesParams, reqEditors ...RequestEditorFn) (*GetTopCategoriesResponse, error)

	// GetTopDomainsByCategoryWithResponse request
	GetTopDomainsByCategoryWithResponse(ctx context.Context, params *GetTopDomainsByCategoryParams, reqEditors ...RequestEditorFn) (*GetTopDomainsByCategoryResponse, error)

	// GetCustomersReportDashboardWithResponse request
	GetCustomersReportDashboardWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCustomersReportDashboardResponse, error)

	// GetHistoricalDnsLogsWithResponse request
	GetHistoricalDnsLogsWithResponse(ctx context.Context, params *GetHistoricalDnsLogsParams, reqEditors ...RequestEditorFn) (*GetHistoricalDnsLogsResponse, error)

	// GetTopDomainsWithResponse request
	GetTopDomainsWithResponse(ctx context.Context, params *GetTopDomainsParams, reqEditors ...RequestEditorFn) (*GetTopDomainsResponse, error)

	// GetStatisticsWithResponse request
	GetStatisticsWithResponse(ctx context.Context, params *GetStatisticsParams, reqEditors ...RequestEditorFn) (*GetStatisticsResponse, error)
}

type GetTopCategoriesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Categories []struct {
			Allowed    float32 `json:"allowed"`
			Blocked    float32 `json:"blocked"`
			Category   string  `json:"category"`
			Requests   float32 `json:"requests"`
			Unresolved float32 `json:"unresolved"`
		} `json:"categories"`
		Filters struct {
			CategoryIds      *[]openapi_types.UUID                       `json:"categoryIds,omitempty"`
			End              time.Time                                   `json:"end"`
			Granularity      *GetTopCategories200FiltersGranularity      `json:"granularity,omitempty"`
			Limit            *float32                                    `json:"limit,omitempty"`
			Metric           *GetTopCategories200FiltersMetric           `json:"metric,omitempty"`
			NetworkIds       *[]openapi_types.UUID                       `json:"networkIds,omitempty"`
			OrganizationIds  *[]openapi_types.UUID                       `json:"organizationIds,omitempty"`
			PolicyIds        *[]openapi_types.UUID                       `json:"policyIds,omitempty"`
			ProtectionModule *GetTopCategories200FiltersProtectionModule `json:"protectionModule,omitempty"`
			Reason           *GetTopCategories200FiltersReason           `json:"reason,omitempty"`
			Start            time.Time                                   `json:"start"`
		} `json:"filters"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON422 *BadRequestResponse
	JSON500 *ServerErrorResponse
}
type GetTopCategories200FiltersGranularity string
type GetTopCategories200FiltersMetric string
type GetTopCategories200FiltersProtectionModule string
type GetTopCategories200FiltersReason string

// Status returns HTTPResponse.Status
func (r GetTopCategoriesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTopCategoriesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTopDomainsByCategoryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		DomainsByCategory []struct {
			Category string `json:"category"`
			Domains  []struct {
				Allowed    float32 `json:"allowed"`
				Blocked    float32 `json:"blocked"`
				Domain     string  `json:"domain"`
				Requests   float32 `json:"requests"`
				Unresolved float32 `json:"unresolved"`
			} `json:"domains"`
		} `json:"domainsByCategory"`
		Filters struct {
			CategoryIds      *[]openapi_types.UUID                              `json:"categoryIds,omitempty"`
			End              time.Time                                          `json:"end"`
			Granularity      *GetTopDomainsByCategory200FiltersGranularity      `json:"granularity,omitempty"`
			Limit            *float32                                           `json:"limit,omitempty"`
			Metric           *GetTopDomainsByCategory200FiltersMetric           `json:"metric,omitempty"`
			NetworkIds       *[]openapi_types.UUID                              `json:"networkIds,omitempty"`
			OrganizationIds  *[]openapi_types.UUID                              `json:"organizationIds,omitempty"`
			PolicyIds        *[]openapi_types.UUID                              `json:"policyIds,omitempty"`
			ProtectionModule *GetTopDomainsByCategory200FiltersProtectionModule `json:"protectionModule,omitempty"`
			Reason           *GetTopDomainsByCategory200FiltersReason           `json:"reason,omitempty"`
			Start            time.Time                                          `json:"start"`
		} `json:"filters"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON422 *BadRequestResponse
	JSON500 *ServerErrorResponse
}
type GetTopDomainsByCategory200FiltersGranularity string
type GetTopDomainsByCategory200FiltersMetric string
type GetTopDomainsByCategory200FiltersProtectionModule string
type GetTopDomainsByCategory200FiltersReason string

// Status returns HTTPResponse.Status
func (r GetTopDomainsByCategoryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTopDomainsByCategoryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCustomersReportDashboardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		Allowed        float32 `json:"allowed"`
		Blocked        float32 `json:"blocked"`
		OrganizationId string  `json:"organizationId"`
		Requests       float32 `json:"requests"`
		Unresolved     float32 `json:"unresolved"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON500 *ServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetCustomersReportDashboardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCustomersReportDashboardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHistoricalDnsLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		Action                   GetHistoricalDnsLogs200Action    `json:"action"`
		CategoryCode             string                           `json:"categoryCode"`
		CountryCode              *string                          `json:"countryCode,omitempty"`
		EdnsTag                  *string                          `json:"ednsTag"`
		FullyQualifiedDomainName string                           `json:"fullyQualifiedDomainName"`
		NetworkId                string                           `json:"networkId"`
		OrganizationId           string                           `json:"organizationId"`
		PolicyId                 string                           `json:"policyId"`
		QueryType                GetHistoricalDnsLogs200QueryType `json:"queryType"`
		Reason                   GetHistoricalDnsLogs200Reason    `json:"reason"`
		ServerId                 string                           `json:"serverId"`
		SourceIpAddress          string                           `json:"sourceIpAddress"`
		Timestamp                time.Time                        `json:"timestamp"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON422 *BadRequestResponse
	JSON500 *ServerErrorResponse
}
type GetHistoricalDnsLogs200Action string
type GetHistoricalDnsLogs200QueryType string
type GetHistoricalDnsLogs200Reason string

// Status returns HTTPResponse.Status
func (r GetHistoricalDnsLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHistoricalDnsLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTopDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Domains []struct {
			Allowed    float32 `json:"allowed"`
			Blocked    float32 `json:"blocked"`
			Domain     string  `json:"domain"`
			Requests   float32 `json:"requests"`
			Unresolved float32 `json:"unresolved"`
		} `json:"domains"`
		Filters struct {
			CategoryIds      *[]openapi_types.UUID                    `json:"categoryIds,omitempty"`
			End              time.Time                                `json:"end"`
			Granularity      *GetTopDomains200FiltersGranularity      `json:"granularity,omitempty"`
			Limit            *float32                                 `json:"limit,omitempty"`
			Metric           *GetTopDomains200FiltersMetric           `json:"metric,omitempty"`
			NetworkIds       *[]openapi_types.UUID                    `json:"networkIds,omitempty"`
			OrganizationIds  *[]openapi_types.UUID                    `json:"organizationIds,omitempty"`
			PolicyIds        *[]openapi_types.UUID                    `json:"policyIds,omitempty"`
			ProtectionModule *GetTopDomains200FiltersProtectionModule `json:"protectionModule,omitempty"`
			Reason           *GetTopDomains200FiltersReason           `json:"reason,omitempty"`
			Start            time.Time                                `json:"start"`
		} `json:"filters"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON422 *BadRequestResponse
	JSON500 *ServerErrorResponse
}
type GetTopDomains200FiltersGranularity string
type GetTopDomains200FiltersMetric string
type GetTopDomains200FiltersProtectionModule string
type GetTopDomains200FiltersReason string

// Status returns HTTPResponse.Status
func (r GetTopDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTopDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetStatisticsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Filters struct {
			CategoryIds      *[]openapi_types.UUID                    `json:"categoryIds,omitempty"`
			End              time.Time                                `json:"end"`
			Granularity      *GetStatistics200FiltersGranularity      `json:"granularity,omitempty"`
			Limit            *float32                                 `json:"limit,omitempty"`
			Metric           *GetStatistics200FiltersMetric           `json:"metric,omitempty"`
			NetworkIds       *[]openapi_types.UUID                    `json:"networkIds,omitempty"`
			OrganizationIds  *[]openapi_types.UUID                    `json:"organizationIds,omitempty"`
			PolicyIds        *[]openapi_types.UUID                    `json:"policyIds,omitempty"`
			ProtectionModule *GetStatistics200FiltersProtectionModule `json:"protectionModule,omitempty"`
			Reason           *GetStatistics200FiltersReason           `json:"reason,omitempty"`
			Start            time.Time                                `json:"start"`
		} `json:"filters"`
		Intervals []struct {
			Allowed    float32   `json:"allowed"`
			Blocked    float32   `json:"blocked"`
			End        time.Time `json:"end"`
			Requests   float32   `json:"requests"`
			Start      time.Time `json:"start"`
			Unresolved float32   `json:"unresolved"`
		} `json:"intervals"`
		Statistics struct {
			Allowed    float32 `json:"allowed"`
			Blocked    float32 `json:"blocked"`
			Requests   float32 `json:"requests"`
			Unresolved float32 `json:"unresolved"`
		} `json:"statistics"`
	}
	JSON401 *UnauthorizedResponse
	JSON403 *ForbiddenResponse
	JSON404 *NotFoundResponse
	JSON422 *BadRequestResponse
	JSON500 *ServerErrorResponse
}
type GetStatistics200FiltersGranularity string
type GetStatistics200FiltersMetric string
type GetStatistics200FiltersProtectionModule string
type GetStatistics200FiltersReason string

// Status returns HTTPResponse.Status
func (r GetStatisticsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetStatisticsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetTopCategoriesWithResponse request returning *GetTopCategoriesResponse
func (c *ClientWithResponses) GetTopCategoriesWithResponse(ctx context.Context, params *GetTopCategoriesParams, reqEditors ...RequestEditorFn) (*GetTopCategoriesResponse, error) {
	rsp, err := c.GetTopCategories(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTopCategoriesResponse(rsp)
}

// GetTopDomainsByCategoryWithResponse request returning *GetTopDomainsByCategoryResponse
func (c *ClientWithResponses) GetTopDomainsByCategoryWithResponse(ctx context.Context, params *GetTopDomainsByCategoryParams, reqEditors ...RequestEditorFn) (*GetTopDomainsByCategoryResponse, error) {
	rsp, err := c.GetTopDomainsByCategory(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTopDomainsByCategoryResponse(rsp)
}

// GetCustomersReportDashboardWithResponse request returning *GetCustomersReportDashboardResponse
func (c *ClientWithResponses) GetCustomersReportDashboardWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCustomersReportDashboardResponse, error) {
	rsp, err := c.GetCustomersReportDashboard(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCustomersReportDashboardResponse(rsp)
}

// GetHistoricalDnsLogsWithResponse request returning *GetHistoricalDnsLogsResponse
func (c *ClientWithResponses) GetHistoricalDnsLogsWithResponse(ctx context.Context, params *GetHistoricalDnsLogsParams, reqEditors ...RequestEditorFn) (*GetHistoricalDnsLogsResponse, error) {
	rsp, err := c.GetHistoricalDnsLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHistoricalDnsLogsResponse(rsp)
}

// GetTopDomainsWithResponse request returning *GetTopDomainsResponse
func (c *ClientWithResponses) GetTopDomainsWithResponse(ctx context.Context, params *GetTopDomainsParams, reqEditors ...RequestEditorFn) (*GetTopDomainsResponse, error) {
	rsp, err := c.GetTopDomains(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTopDomainsResponse(rsp)
}

// GetStatisticsWithResponse request returning *GetStatisticsResponse
func (c *ClientWithResponses) GetStatisticsWithResponse(ctx context.Context, params *GetStatisticsParams, reqEditors ...RequestEditorFn) (*GetStatisticsResponse, error) {
	rsp, err := c.GetStatistics(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetStatisticsResponse(rsp)
}

// ParseGetTopCategoriesResponse parses an HTTP response from a GetTopCategoriesWithResponse call
func ParseGetTopCategoriesResponse(rsp *http.Response) (*GetTopCategoriesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTopCategoriesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Categories []struct {
				Allowed    float32 `json:"allowed"`
				Blocked    float32 `json:"blocked"`
				Category   string  `json:"category"`
				Requests   float32 `json:"requests"`
				Unresolved float32 `json:"unresolved"`
			} `json:"categories"`
			Filters struct {
				CategoryIds      *[]openapi_types.UUID                       `json:"categoryIds,omitempty"`
				End              time.Time                                   `json:"end"`
				Granularity      *GetTopCategories200FiltersGranularity      `json:"granularity,omitempty"`
				Limit            *float32                                    `json:"limit,omitempty"`
				Metric           *GetTopCategories200FiltersMetric           `json:"metric,omitempty"`
				NetworkIds       *[]openapi_types.UUID                       `json:"networkIds,omitempty"`
				OrganizationIds  *[]openapi_types.UUID                       `json:"organizationIds,omitempty"`
				PolicyIds        *[]openapi_types.UUID                       `json:"policyIds,omitempty"`
				ProtectionModule *GetTopCategories200FiltersProtectionModule `json:"protectionModule,omitempty"`
				Reason           *GetTopCategories200FiltersReason           `json:"reason,omitempty"`
				Start            time.Time                                   `json:"start"`
			} `json:"filters"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTopDomainsByCategoryResponse parses an HTTP response from a GetTopDomainsByCategoryWithResponse call
func ParseGetTopDomainsByCategoryResponse(rsp *http.Response) (*GetTopDomainsByCategoryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTopDomainsByCategoryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			DomainsByCategory []struct {
				Category string `json:"category"`
				Domains  []struct {
					Allowed    float32 `json:"allowed"`
					Blocked    float32 `json:"blocked"`
					Domain     string  `json:"domain"`
					Requests   float32 `json:"requests"`
					Unresolved float32 `json:"unresolved"`
				} `json:"domains"`
			} `json:"domainsByCategory"`
			Filters struct {
				CategoryIds      *[]openapi_types.UUID                              `json:"categoryIds,omitempty"`
				End              time.Time                                          `json:"end"`
				Granularity      *GetTopDomainsByCategory200FiltersGranularity      `json:"granularity,omitempty"`
				Limit            *float32                                           `json:"limit,omitempty"`
				Metric           *GetTopDomainsByCategory200FiltersMetric           `json:"metric,omitempty"`
				NetworkIds       *[]openapi_types.UUID                              `json:"networkIds,omitempty"`
				OrganizationIds  *[]openapi_types.UUID                              `json:"organizationIds,omitempty"`
				PolicyIds        *[]openapi_types.UUID                              `json:"policyIds,omitempty"`
				ProtectionModule *GetTopDomainsByCategory200FiltersProtectionModule `json:"protectionModule,omitempty"`
				Reason           *GetTopDomainsByCategory200FiltersReason           `json:"reason,omitempty"`
				Start            time.Time                                          `json:"start"`
			} `json:"filters"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetCustomersReportDashboardResponse parses an HTTP response from a GetCustomersReportDashboardWithResponse call
func ParseGetCustomersReportDashboardResponse(rsp *http.Response) (*GetCustomersReportDashboardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCustomersReportDashboardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			Allowed        float32 `json:"allowed"`
			Blocked        float32 `json:"blocked"`
			OrganizationId string  `json:"organizationId"`
			Requests       float32 `json:"requests"`
			Unresolved     float32 `json:"unresolved"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetHistoricalDnsLogsResponse parses an HTTP response from a GetHistoricalDnsLogsWithResponse call
func ParseGetHistoricalDnsLogsResponse(rsp *http.Response) (*GetHistoricalDnsLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHistoricalDnsLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			Action                   GetHistoricalDnsLogs200Action    `json:"action"`
			CategoryCode             string                           `json:"categoryCode"`
			CountryCode              *string                          `json:"countryCode,omitempty"`
			EdnsTag                  *string                          `json:"ednsTag"`
			FullyQualifiedDomainName string                           `json:"fullyQualifiedDomainName"`
			NetworkId                string                           `json:"networkId"`
			OrganizationId           string                           `json:"organizationId"`
			PolicyId                 string                           `json:"policyId"`
			QueryType                GetHistoricalDnsLogs200QueryType `json:"queryType"`
			Reason                   GetHistoricalDnsLogs200Reason    `json:"reason"`
			ServerId                 string                           `json:"serverId"`
			SourceIpAddress          string                           `json:"sourceIpAddress"`
			Timestamp                time.Time                        `json:"timestamp"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetTopDomainsResponse parses an HTTP response from a GetTopDomainsWithResponse call
func ParseGetTopDomainsResponse(rsp *http.Response) (*GetTopDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTopDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Domains []struct {
				Allowed    float32 `json:"allowed"`
				Blocked    float32 `json:"blocked"`
				Domain     string  `json:"domain"`
				Requests   float32 `json:"requests"`
				Unresolved float32 `json:"unresolved"`
			} `json:"domains"`
			Filters struct {
				CategoryIds      *[]openapi_types.UUID                    `json:"categoryIds,omitempty"`
				End              time.Time                                `json:"end"`
				Granularity      *GetTopDomains200FiltersGranularity      `json:"granularity,omitempty"`
				Limit            *float32                                 `json:"limit,omitempty"`
				Metric           *GetTopDomains200FiltersMetric           `json:"metric,omitempty"`
				NetworkIds       *[]openapi_types.UUID                    `json:"networkIds,omitempty"`
				OrganizationIds  *[]openapi_types.UUID                    `json:"organizationIds,omitempty"`
				PolicyIds        *[]openapi_types.UUID                    `json:"policyIds,omitempty"`
				ProtectionModule *GetTopDomains200FiltersProtectionModule `json:"protectionModule,omitempty"`
				Reason           *GetTopDomains200FiltersReason           `json:"reason,omitempty"`
				Start            time.Time                                `json:"start"`
			} `json:"filters"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetStatisticsResponse parses an HTTP response from a GetStatisticsWithResponse call
func ParseGetStatisticsResponse(rsp *http.Response) (*GetStatisticsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetStatisticsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Filters struct {
				CategoryIds      *[]openapi_types.UUID                    `json:"categoryIds,omitempty"`
				End              time.Time                                `json:"end"`
				Granularity      *GetStatistics200FiltersGranularity      `json:"granularity,omitempty"`
				Limit            *float32                                 `json:"limit,omitempty"`
				Metric           *GetStatistics200FiltersMetric           `json:"metric,omitempty"`
				NetworkIds       *[]openapi_types.UUID                    `json:"networkIds,omitempty"`
				OrganizationIds  *[]openapi_types.UUID                    `json:"organizationIds,omitempty"`
				PolicyIds        *[]openapi_types.UUID                    `json:"policyIds,omitempty"`
				ProtectionModule *GetStatistics200FiltersProtectionModule `json:"protectionModule,omitempty"`
				Reason           *GetStatistics200FiltersReason           `json:"reason,omitempty"`
				Start            time.Time                                `json:"start"`
			} `json:"filters"`
			Intervals []struct {
				Allowed    float32   `json:"allowed"`
				Blocked    float32   `json:"blocked"`
				End        time.Time `json:"end"`
				Requests   float32   `json:"requests"`
				Start      time.Time `json:"start"`
				Unresolved float32   `json:"unresolved"`
			} `json:"intervals"`
			Statistics struct {
				Allowed    float32 `json:"allowed"`
				Blocked    float32 `json:"blocked"`
				Requests   float32 `json:"requests"`
				Unresolved float32 `json:"unresolved"`
			} `json:"statistics"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
